[package]
name = "manger-core"
version = "0.1.1"
authors = ["Gijs Burghoorn <me@gburghoorn.com>"]
edition = "2018"
categories = ["parsing"]
keywords = ["combinatoric", "parser", "consume"]
repository = "https://github.com/coastalwhite/manger"
homepage = "https://github.com/coastalwhite/manger"
license = "MIT"
description = "A performant, low-level, lightweight and intuitive combinatoric parser library"

[badges.maintenance]
status = "actively-developed"

[dependencies]
utf8_slice = "^1.0.0"
either = "1.6.1"
thiserror = "1.0"

[dev-dependencies]
manger = { version = "0.1.1",  path = "../../" }
